version: "3.8"

services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=troquinhas-rest-api
    ports:
      - "3306"
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - mysql
    image: troquinhas/troquinhas:1.0
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysql:3306/troquinhas-rest-api?useSSL=false",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "root",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "create-drop",

            "security.jwt.expiracao": "3600",
            "security.jwt.chave-assinatura": "VW1hIGNlcnZlamEgYW50ZXMgZG8gYWxtb8OnbyDDqSBtdWl0byBib20gcHJhIGZpY2FyIHBlbnNhbmRvIG1lbGhvcg==",

            "spring.jpa.show-sql":"true",
            "spring.jpa.properties.hibernate.dialect":"org.hibernate.dialect.MySQL8Dialect",
            "spring.jpa.properties.hibernate.format_sql":"true",
            "spring.jpa.defer-datasource-initialization":"true",
            "spring.datasource.driver-class-name":"com.mysql.cj.jdbc.Driver",
            "spring.sql.init.mode":"always",
            
            "spring.mvc.pathmatch.matching-strategy":"ANT_PATH_MATCHER"
          }'
    volumes:
      - .m2:/root/.m2

volumes:
  db: